### PR TITLE
feat: implement reading/saving response using provided buffer

### LINKED ISSUE #8: [FR] `Response.readinto` is desired.
It would be nicer if `Response` class had a `readinto` method.
When reading from chunked responses, a memory constrained device may want to reuse a `bytearray` instead of allocating a new `bytearray` or `bytes` object every time.

### PR DESCRIPTION
**Pull request by SpotlightKid**
Fixes: #8
Obsoletes: #10

### CODE REVIEW

**Comment by ubidefeo** [comment]
hey @SpotlightKid 

I've been following (and using) mrequests for a bit, looking for ways to contribute, so I just forked it.
I have a question about this PR and about something I'd like to implement.

Consider it some sort of brainstorming, more than a proposed solution 😄 

I like that with these changes we can use buffers, but when `save()` is invoked, the response is already done, and data is already in memory, ready to be transferred to an open stream.
This allows us to interact with the data, but I'd like to have file download progress by either wrapping `get()` or adding a parameter (a buffer/stream) to it.
I think wrapping allows for neater semantics, without too much augmenting of something as legacy as `get()`.

I'm using mrequests to download tar archives, so I was wondering if it's a good idea to tap into this (or any other more favourable point, haven't read through it all)

```python
resp = response_class(sock, sf, save_headers=save_headers)
l = b""
i = 0
while True:
    l += sf.read(1)
    i += 1

    if l.endswith(b"\r\n") or i > MAX_READ_SIZE:
        break
```

I'm really interested in download progress, rather than saving data after the fact :) 

Let me knwo what you think about it and if it's something you'd see as useful

thank you
u.

**Comment by SpotlightKid** [comment]
> [...] when `save()` is invoked, the response is already done, and data is already in memory,

Not true. When `request` returns, only the response headers have been read from the network. The returned `Response` class instance is doing the actual retrieval of the response body, either when you access `content` or `text` properties for the first time or call `json` or `save`, `read` or `readinto`.

> ```python
> resp = response_class(sock, sf, save_headers=save_headers)
> l = b""
> i = 0
> while True:
>     l += sf.read(1)
>     i += 1
> 
>     if l.endswith(b"\r\n") or i > MAX_READ_SIZE:
>         break

This code is only for reading the response headers.

> I'm really interested in download progress, rather than saving data after the fact :)

With the version of `mrequests` in this PR you can already achieve that:

```py
import mrequests

buf = bytearray(1024)

class ResponseWithProgress(mrequests.Response):
    _total_read = 0

    def readinto(self, buf, size=0):
        bytes_read = super().readinto(buf, size)
        self._total_read += bytes_read
        print("Progress: {:.2f}%".format(self._total_read / (self._content_size * 0.01)))
        return bytes_read

r = mrequests.get('http://httpbin.org/image.png', headers={b"accept": b"image/png"}, response_class=ResponseWithProgress)

if r.status_code == 200:
    r.save(filename, buf=buf)
    print("Image saved to '{}'.".format(filename))
else:
    print("Request failed. Status: {}".format(r.status_code))

r.close()
```

Output:

```
Progress: 12.66%
Progress: 25.32%
Progress: 37.97%
Progress: 50.63%
Progress: 63.29%
Progress: 75.95%
Progress: 88.60%
Progress: 100.00%
Image saved to 'image.png'.
```

**Comment by ubidefeo** [comment]
>Not true. When request returns, only the response headers have been read from the network. The returned Response class instance is doing the actual retrieval of the response body, either when you access content or text properties for the first time or call json or save, read or readinto.

This was exactly the part I didn't fully understand!
Thank you so much for explaining it.
I did get to the point of retrieving the header, but then got lost further on.

The example for extending `mrequests.Response` is going to be extremely beneficial to my use case, I'm beyond thankful :)

How does the review process work on this repo?
I can't see other contributors, who's going to review/approve your PRs?

This last addition is definitely something I want to use :)

Let me know if/how I can help.
The code changes look good, testing it on my end sure could offer an informed use review, but I don't want to barge into your process

u.

**Comment by SpotlightKid** [comment]
> I can't see other contributors, who's going to review/approve your PRs?
> [...]
> Let me know if/how I can help.

Yeah, there's only me. I haven't merged this PR yet, because I haven't tested it on each supported MicroPython port. Doing so manually (after each change) would be extremely cumbersome, so I would like to have a script, which installs the latest version and runs some functional test on a board with just one command. The new [mpremote](https://pypi.org/project/mpremote/) tool might help with that. Plus some unit tests for the `Response` class at least. 

This is mainly grunt work, not the most exciting thing to do, so I haven't managed to find the time for it. Any help with that would be appreciated.

**Comment by ubidefeo** [comment]
we use `mpremote` all the time, I'm happy to make an install script to copy the files and run the example.
I have a MP webinar with Espressif tomorrow, but after that I'll have more time :)

I'm also thinking that I'll submit a PR to enable `mip` support so users can install it simply as follows

```
import mip
mip.install('github:SpotlightKid/mrequests')
```

I plan on installing it on my upcoming project, the one for which I'll need download progress ;)

**Comment by SpotlightKid** [comment]
> I'm happy to make an install script to copy the files

There's already [install.sh](https://github.com/SpotlightKid/mrequests/blob/master/install.sh), which uses `rshell` and can probably be easily adapted.

**Comment by SpotlightKid** [comment]
> I'm also thinking that I'll submit a PR to enable `mip` support

That would be very welcome. Please open a separate PR for this.

**Comment by ubidefeo** [comment]
>That would be very welcome. Please open a separate PR for this.

of course :)

**Pull request merged**
